sylius_mailer:
    emails:
        invoice_generated:
            subject: sylius.emails.invoice_generated.subject
            template: "@SyliusInvoicingPlugin/Resources/views/Invoice/Email/invoiceGenerated.html.twig"

knp_snappy:
    pdf:
        enabled: true
        binary: /usr/local/bin/wkhtmltopdf
        options: []

sylius_channel:
    resources:
        channel:
            classes:
                model: Tests\Application\InvoicingPlugin\AppBundle\Entity\Channel
